//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int32_t _ZdlPvS_(int32_t a1, int32_t a2);
int32_t _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE10deallocateEPS5_j(int32_t * a1, int32_t a2, int32_t a3);
int32_t _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE7destroyIS4_EEvPT_(int32_t a1, int32_t a2);
int32_t _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE8allocateEjPKv(int32_t a1, uint32_t a2, int32_t a3);
int32_t _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE9constructIS4_JRKSt21piecewise_construct_tSt5tupleIJOcEESB_IJEEEEEvPT_DpOT0_(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEEC1Ev(int32_t a1);
int32_t _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEED1Ev(int32_t a1);
int32_t _ZN9__gnu_cxx16__aligned_membufISt4pairIKciEE6_M_ptrEv(int32_t a1);
int32_t _ZN9__gnu_cxx16__aligned_membufISt4pairIKciEE7_M_addrEv(int32_t result);
int32_t _ZNK9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE8max_sizeEv(int32_t a1);
int32_t _ZNK9__gnu_cxx16__aligned_membufISt4pairIKciEE6_M_ptrEv(int32_t a1);
int32_t _ZNK9__gnu_cxx16__aligned_membufISt4pairIKciEE7_M_addrEv(int32_t result);
int32_t _ZNKSt10_Select1stISt4pairIKciEEclERKS2_(int32_t result, int32_t a2);
int32_t _ZNKSt13_Rb_tree_nodeISt4pairIKciEE9_M_valptrEv(int32_t a1);
int32_t _ZNKSt17_Rb_tree_iteratorISt4pairIKciEEdeEv(int32_t * a1);
int32_t _ZNKSt17_Rb_tree_iteratorISt4pairIKciEEeqERKS3_(int32_t * a1, int32_t a2);
int32_t _ZNKSt23_Rb_tree_const_iteratorISt4pairIKciEE13_M_const_castEv(int32_t result, int32_t * a2);
int32_t _ZNKSt3mapIciSt4lessIcESaISt4pairIKciEEE8key_compEv(int32_t a1, int32_t a2);
int32_t _ZNKSt4lessIcEclERKcS2_(char * a1, int32_t a2, int32_t a3);
int32_t _ZNKSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE4sizeEv(int32_t a1);
int32_t _ZNKSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8key_compEv(int32_t result, int32_t a2);
int32_t _ZNSaISt13_Rb_tree_nodeISt4pairIKciEEEC1Ev(int32_t a1);
int32_t _ZNSaISt13_Rb_tree_nodeISt4pairIKciEEED1Ev(int32_t a1);
int32_t _ZNSt10_Head_baseILj0EOcLb0EE7_M_headERS1_(int32_t * a1);
int32_t _ZNSt10_Head_baseILj0EOcLb0EEC1IcEEOT_(int32_t * a1, int32_t a2);
int32_t _ZNSt11_Tuple_implILj0EJOcEE7_M_headERS1_(int32_t a1);
int32_t _ZNSt11_Tuple_implILj0EJOcEEC1EOS1_(int32_t a1, int32_t a2);
int32_t _ZNSt11_Tuple_implILj0EJOcEEC1IcEEOT_(int32_t a1, int32_t a2);
int32_t _ZNSt13_Rb_tree_nodeISt4pairIKciEE9_M_valptrEv(int32_t a1);
int32_t _ZNSt15_Rb_tree_header8_M_resetEv(int32_t result);
int32_t _ZNSt15_Rb_tree_headerC1Ev(int32_t * a1);
int32_t _ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKciEEEE10deallocateERS5_PS4_j(int32_t a1, int32_t a2, int32_t a3);
int32_t _ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKciEEEE7destroyIS3_EEvRS5_PT_(int32_t a1, int32_t a2);
int32_t _ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKciEEEE8allocateERS5_j(int32_t a1, int32_t a2);
int32_t _ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKciEEEE9constructIS3_JRKSt21piecewise_construct_tSt5tupleIJOcEESB_IJEEEEEvRS5_PT_DpOT0_(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t _ZNSt17_Rb_tree_iteratorISt4pairIKciEEC1EPSt18_Rb_tree_node_base(int32_t * a1, int32_t a2);
int32_t _ZNSt17_Rb_tree_iteratorISt4pairIKciEEmmEv(int32_t * a1);
int32_t _ZNSt17_Rb_tree_iteratorISt4pairIKciEEppEv(int32_t * a1);
int32_t _ZNSt20_Rb_tree_key_compareISt4lessIcEEC1Ev(int32_t a1);
int32_t _ZNSt23_Rb_tree_const_iteratorISt4pairIKciEEC1ERKSt17_Rb_tree_iteratorIS2_E(void);
int32_t _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEE11lower_boundERS3_(int32_t a1, int32_t a2, int32_t a3);
int32_t _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEE3endEv(int32_t a1, int32_t a2);
int32_t _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEEC1Ev(int32_t a1);
int32_t _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEED1Ev(int32_t a1);
int32_t _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEEixEOc(int32_t a1, int32_t a2);
int32_t _ZNSt4pairIKciEC1IJOcEJEEESt21piecewise_construct_tSt5tupleIJDpT_EES5_IJDpT0_EE(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t _ZNSt4pairIKciEC1IJOcEJLj0EEJEJEEERSt5tupleIJDpT_EERS4_IJDpT1_EESt12_Index_tupleIJXspT0_EEESD_IJXspT2_EEE(char * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRPSt13_Rb_tree_nodeIS_IKciEERS1_Lb1EEEOT_OT0_(void);
int32_t _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_Lb1EEEOT_RKS1_(int32_t * a1, int32_t a2, int32_t a3);
int32_t _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_Lb1EEERKS1_OT_(int32_t * a1, int32_t a2, int32_t a3);
int32_t _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_S4_Lb1EEEOT_OT0_(int32_t * a1, int32_t a2, int32_t a3);
int32_t _ZNSt5tupleIJOcEEC1EOS1_(int32_t a1, int32_t a2);
int32_t _ZNSt5tupleIJOcEEC1IJcELb1EEEDpOT_(int32_t a1, int32_t a2);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11_M_get_nodeEv(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11_M_leftmostEv(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11_M_put_nodeEPSt13_Rb_tree_nodeIS2_E(int32_t a1, int32_t a2);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11lower_boundERS1_(int32_t a1, int32_t a2, int32_t a3);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE12_M_drop_nodeEPSt13_Rb_tree_nodeIS2_E(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE12_M_rightmostEv(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE13_Rb_tree_implIS6_Lb1EEC1Ev(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE13_Rb_tree_implIS6_Lb1EED1Ev(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE14_M_create_nodeIJRKSt21piecewise_construct_tSt5tupleIJOcEESD_IJEEEEEPSt13_Rb_tree_nodeIS2_EDpOT_(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE14_M_insert_nodeEPSt18_Rb_tree_node_baseSA_PSt13_Rb_tree_nodeIS2_E(int32_t result, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE14_M_lower_boundEPSt13_Rb_tree_nodeIS2_EPSt18_Rb_tree_node_baseRS1_(int32_t result, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE15_M_destroy_nodeEPSt13_Rb_tree_nodeIS2_E(int32_t a1, int32_t a2);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE17_M_construct_nodeIJRKSt21piecewise_construct_tSt5tupleIJOcEESD_IJEEEEEvPSt13_Rb_tree_nodeIS2_EDpOT_(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE21_M_get_Node_allocatorEv(int32_t result);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE22_M_emplace_hint_uniqueIJRKSt21piecewise_construct_tSt5tupleIJOcEESD_IJEEEEESt17_Rb_tree_iteratorIS2_ESt23_Rb_tree_const_iteratorIS2_EDpOT_(void);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE24_M_get_insert_unique_posERS1_(int32_t a1, int32_t a2, int32_t a3);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE29_M_get_insert_hint_unique_posESt23_Rb_tree_const_iteratorIS2_ERS1_(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE3endEv(int32_t result, int32_t a2);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE5beginEv(void);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_M_endEv(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt13_Rb_tree_nodeIS2_E(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt18_Rb_tree_node_base(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE7_S_leftEPSt18_Rb_tree_node_base(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_M_beginEv(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_M_eraseEPSt13_Rb_tree_nodeIS2_E(int32_t a1, int32_t a2);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_rightEPSt18_Rb_tree_node_base(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_valueEPKSt13_Rb_tree_nodeIS2_E(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_valueEPKSt18_Rb_tree_node_base(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EEC1Ev(int32_t a1);
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EED1Ev(int32_t a1);
int32_t _ZnwjPv(int32_t result, int32_t a2);
int32_t _ZSt12__get_helperILj0EOcJEERT0_RSt11_Tuple_implIXT_EJS1_DpT1_EE(int32_t a1);
int32_t _ZSt16forward_as_tupleIJcEESt5tupleIJDpOT_EES3_(void);
int32_t _ZSt3getILj0EJOcEERNSt13tuple_elementIXT_ESt5tupleIJDpT0_EEE4typeERS5_(int32_t a1);
int32_t _ZSt4moveIRcEONSt16remove_referenceIT_E4typeEOS2_(void);
int32_t _ZSt7forwardIcEOT_RNSt16remove_referenceIS0_E4typeE(int32_t result);
int32_t _ZSt7forwardIOcEOT_RNSt16remove_referenceIS1_E4typeE(int32_t result);
int32_t _ZSt7forwardIRKSt21piecewise_construct_tEOT_RNSt16remove_referenceIS3_E4typeE(int32_t result);
int32_t _ZSt7forwardIRPSt13_Rb_tree_nodeISt4pairIKciEEEOT_RNSt16remove_referenceIS7_E4typeE(int32_t result);
int32_t _ZSt7forwardIRPSt18_Rb_tree_node_baseEOT_RNSt16remove_referenceIS3_E4typeE(int32_t result);
int32_t _ZSt7forwardISt5tupleIJEEEOT_RNSt16remove_referenceIS2_E4typeE(int32_t result);
int32_t _ZSt7forwardISt5tupleIJOcEEEOT_RNSt16remove_referenceIS3_E4typeE(int32_t result);
int32_t function_8049040(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_8049050(void);
int32_t function_8049060(int32_t a1);
int32_t function_8049070(int32_t a1);
int32_t function_80490a0(int32_t a1);
int32_t function_80490c0(void);
int32_t function_80490d0(void);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // eax
int32_t g2 = 0; // ebp
int32_t g3 = 0; // ebx
int32_t g4 = 0; // ecx
int32_t g5 = 0; // edi
int32_t g6 = 0; // edx
int32_t g7 = 0; // esi
int32_t g8 = 0; // esp

// ------------------------ Functions -------------------------

// Address range: 0x8049040 - 0x8049046
int32_t function_8049040(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x8049040
    return _ZSt29_Rb_tree_insert_and_rebalancebPSt18_Rb_tree_node_baseS0_RS_();
}

// Address range: 0x8049050 - 0x8049056
int32_t function_8049050(void) {
    // 0x8049050
    return _ZSt17__throw_bad_allocv();
}

// Address range: 0x8049060 - 0x8049066
int32_t function_8049060(int32_t a1) {
    // 0x8049060
    return __cxa_begin_catch();
}

// Address range: 0x8049070 - 0x8049076
int32_t function_8049070(int32_t a1) {
    // 0x8049070
    return _ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base();
}

// Address range: 0x80490a0 - 0x80490a6
int32_t function_80490a0(int32_t a1) {
    // 0x80490a0
    return _ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base();
}

// Address range: 0x80490c0 - 0x80490c6
int32_t function_80490c0(void) {
    // 0x80490c0
    return __cxa_rethrow();
}

// Address range: 0x80490d0 - 0x80490d6
int32_t function_80490d0(void) {
    // 0x80490d0
    return __cxa_end_catch();
}

// Address range: 0x8049216 - 0x80492df
int main(int argc, char ** argv) {
    // 0x8049216
    int32_t v1; // bp-44
    int32_t v2 = &v1; // 0x8049236
    _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEEC1Ev(v2);
    char v3 = 97; // bp-45
    int32_t v4 = &v3; // 0x8049249
    *(int32_t *)_ZNSt3mapIciSt4lessIcESaISt4pairIKciEEEixEOc(v2, v4) = 1;
    v3 = 98;
    *(int32_t *)_ZNSt3mapIciSt4lessIcESaISt4pairIKciEEEixEOc(v2, v4) = 2;
    v3 = 97;
    g3 = *(int32_t *)_ZNSt3mapIciSt4lessIcESaISt4pairIKciEEEixEOc(v2, v4);
    _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEED1Ev(v2);
    int32_t result; // 0x80492de
    result = g3;
    // 0x80492d5
    return result;
}

// Address range: 0x80492df - 0x80492e7
int32_t _ZnwjPv(int32_t result, int32_t a2) {
    // 0x80492df
    return result;
}

// Address range: 0x80492e7 - 0x80492ed
int32_t _ZdlPvS_(int32_t a1, int32_t a2) {
    // 0x80492e7
    return g1;
}

// Address range: 0x80492ee - 0x804930e
// Demangled:     std::_Rb_tree_header::_Rb_tree_header()
int32_t _ZNSt15_Rb_tree_headerC1Ev(int32_t * a1) {
    // 0x80492ee
    *a1 = 0;
    return _ZNSt15_Rb_tree_header8_M_resetEv((int32_t)a1);
}

// Address range: 0x804930e - 0x804933a
// Demangled:     std::_Rb_tree_header::_M_reset()
int32_t _ZNSt15_Rb_tree_header8_M_resetEv(int32_t result) {
    // 0x804930e
    *(int32_t *)(result + 4) = 0;
    *(int32_t *)(result + 8) = result;
    *(int32_t *)(result + 12) = result;
    *(int32_t *)(result + 16) = 0;
    return result;
}

// Address range: 0x804933a - 0x8049351
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_Rb_tree_impl<std::less<char>, true>::~_Rb_tree_impl()
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE13_Rb_tree_implIS6_Lb1EED1Ev(int32_t a1) {
    // 0x804933a
    return _ZNSaISt13_Rb_tree_nodeISt4pairIKciEEED1Ev(a1);
}

// Address range: 0x8049352 - 0x804936a
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_Rb_tree()
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EEC1Ev(int32_t a1) {
    // 0x8049352
    g1 = a1;
    return _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE13_Rb_tree_implIS6_Lb1EEC1Ev(a1);
}

// Address range: 0x804936a - 0x8049382
// Demangled:     std::map<char, int, std::less<char>, std::allocator<std::pair<char const, int> > >::map()
int32_t _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEEC1Ev(int32_t a1) {
    // 0x804936a
    return _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EEC1Ev(a1);
}

// Address range: 0x8049382 - 0x804939a
// Demangled:     std::map<char, int, std::less<char>, std::allocator<std::pair<char const, int> > >::~map()
int32_t _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEED1Ev(int32_t a1) {
    // 0x8049382
    return _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EED1Ev(a1);
}

// Address range: 0x804939a - 0x80493d2
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_Rb_tree_impl<std::less<char>, true>::_Rb_tree_impl()
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE13_Rb_tree_implIS6_Lb1EEC1Ev(int32_t a1) {
    // 0x804939a
    _ZNSaISt13_Rb_tree_nodeISt4pairIKciEEEC1Ev(a1);
    g1 = a1;
    _ZNSt20_Rb_tree_key_compareISt4lessIcEEC1Ev(a1);
    return _ZNSt15_Rb_tree_headerC1Ev((int32_t *)(a1 + 4));
}

// Address range: 0x80493d2 - 0x80493e9
// Demangled:     std::allocator<std::_Rb_tree_node<std::pair<char const, int> > >::~allocator()
int32_t _ZNSaISt13_Rb_tree_nodeISt4pairIKciEEED1Ev(int32_t a1) {
    // 0x80493d2
    return _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEED1Ev(a1);
}

// Address range: 0x80493ea - 0x804941f
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::~_Rb_tree()
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EED1Ev(int32_t a1) {
    int32_t v1 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_M_beginEv(a1); // 0x80493f6
    g1 = v1;
    _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_M_eraseEPSt13_Rb_tree_nodeIS2_E(a1, v1);
    g1 = a1;
    return _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE13_Rb_tree_implIS6_Lb1EED1Ev(a1);
}

// Address range: 0x8049420 - 0x8049548
// Demangled:     std::map<char, int, std::less<char>, std::allocator<std::pair<char const, int> > >::operator[](char &&)
int32_t _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEEixEOc(int32_t a1, int32_t a2) {
    int32_t v1 = g3; // 0x8049423
    int32_t v2; // bp-60
    int32_t v3 = &v2; // 0x8049424
    int32_t v4; // bp-28
    int32_t v5 = &v4; // 0x804943e
    int32_t v6 = a2; // bp-68
    int32_t v7 = a1; // bp-72
    int32_t v8 = &v7; // 0x8049447
    _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEE11lower_boundERS3_(v5, a1, a2);
    int32_t v9; // bp-20
    int32_t v10 = &v9; // 0x8049453
    _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEE3endEv(v10, a1);
    int32_t v11; // bp-24
    int32_t v12; // bp-29
    int32_t v13; // 0x80494cd
    int32_t v14; // 0x80494d2
    int32_t v15; // 0x80494e4
    int32_t v16; // 0x80494f7
    int32_t result; // 0x8049547
    int32_t v17;
    int32_t v18; // 0x8049527
    int32_t * v19;
    if ((char)_ZNKSt17_Rb_tree_iteratorISt4pairIKciEEeqERKS3_(&v4, v10) != 0) {
        // 0x80494c0
        // branch -> 0x80494c4
        // 0x80494c4
        v17 = &v11;
        g3 = a1;
        *(int32_t *)((int32_t)&v6 - 16) = a2;
        v13 = _ZSt4moveIRcEONSt16remove_referenceIT_E4typeEOS2_();
        v14 = g8;
        *(int32_t *)(v14 + 4) = v13;
        *(int32_t *)v14 = v17;
        _ZSt16forward_as_tupleIJcEESt5tupleIJDpOT_EES3_();
        v15 = g8;
        *(int32_t *)v15 = v5;
        *(int32_t *)(v15 - 4) = v10;
        _ZNSt23_Rb_tree_const_iteratorISt4pairIKciEEC1ERKSt17_Rb_tree_iteratorIS2_E();
        v16 = g8;
        *(int32_t *)(v16 + 4) = (int32_t)&v12;
        *(int32_t *)v16 = v17;
        *(int32_t *)(v16 - 4) = 0x804b008;
        *(int32_t *)(v16 - 8) = v9;
        *(int32_t *)(v16 - 12) = g3;
        *(int32_t *)(v16 - 16) = v3;
        _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE22_M_emplace_hint_uniqueIJRKSt21piecewise_construct_tSt5tupleIJOcEESD_IJEEEEESt17_Rb_tree_iteratorIS2_ESt23_Rb_tree_const_iteratorIS2_EDpOT_();
        v4 = v2;
        // branch -> 0x8049520
        // 0x8049520
        *(int32_t *)(g8 + 12) = v5;
        v18 = _ZNKSt17_Rb_tree_iteratorISt4pairIKciEEdeEv((int32_t *)v4);
        result = v18 + 4;
        // 0x8049543
        g3 = v1;
        return result;
    }
    // 0x80494c0
    int32_t v20; // bp-53
    _ZNKSt3mapIciSt4lessIcESaISt4pairIKciEEE8key_compEv((int32_t)&v20, a1);
    int32_t v21 = _ZNKSt17_Rb_tree_iteratorISt4pairIKciEEdeEv(&v4); // 0x8049495
    int32_t v22; // 0x8049520
    if ((char)_ZNKSt4lessIcEclERKcS2_((char *)&v11, a2, v21) != 0) {
        // 0x80494c4
        v17 = &v11;
        g3 = a1;
        *(int32_t *)(v8 - 16) = a2;
        v13 = _ZSt4moveIRcEONSt16remove_referenceIT_E4typeEOS2_();
        v14 = g8;
        *(int32_t *)(v14 + 4) = v13;
        *(int32_t *)v14 = v17;
        _ZSt16forward_as_tupleIJcEESt5tupleIJDpOT_EES3_();
        v15 = g8;
        *(int32_t *)v15 = v5;
        *(int32_t *)(v15 - 4) = v10;
        _ZNSt23_Rb_tree_const_iteratorISt4pairIKciEEC1ERKSt17_Rb_tree_iteratorIS2_E();
        v16 = g8;
        *(int32_t *)(v16 + 4) = (int32_t)&v12;
        *(int32_t *)v16 = v17;
        *(int32_t *)(v16 - 4) = 0x804b008;
        *(int32_t *)(v16 - 8) = v9;
        *(int32_t *)(v16 - 12) = g3;
        *(int32_t *)(v16 - 16) = v3;
        _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE22_M_emplace_hint_uniqueIJRKSt21piecewise_construct_tSt5tupleIJOcEESD_IJEEEEESt17_Rb_tree_iteratorIS2_ESt23_Rb_tree_const_iteratorIS2_EDpOT_();
        v4 = v2;
        v22 = g8 + 28;
        // branch -> 0x8049520
    } else {
        v22 = v8;
    }
    // 0x8049520
    *(int32_t *)(v22 - 16) = v5;
    v18 = _ZNKSt17_Rb_tree_iteratorISt4pairIKciEEdeEv((int32_t *)v4);
    result = v18 + 4;
    // 0x8049543
    g3 = v1;
    return result;
}

// Address range: 0x8049548 - 0x804955f
// Demangled:     std::allocator<std::_Rb_tree_node<std::pair<char const, int> > >::allocator()
int32_t _ZNSaISt13_Rb_tree_nodeISt4pairIKciEEEC1Ev(int32_t a1) {
    // 0x8049548
    return _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEEC1Ev(a1);
}

// Address range: 0x8049560 - 0x8049566
// Demangled:     std::_Rb_tree_key_compare<std::less<char> >::_Rb_tree_key_compare()
int32_t _ZNSt20_Rb_tree_key_compareISt4lessIcEEC1Ev(int32_t a1) {
    // 0x8049560
    return g1;
}

// Address range: 0x8049566 - 0x804956c
// Demangled:     __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<char const, int> > >::~new_allocator()
int32_t _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEED1Ev(int32_t a1) {
    // 0x8049566
    return g1;
}

// Address range: 0x804956c - 0x80495c2
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_erase(std::_Rb_tree_node<std::pair<char const, int> > *)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_M_eraseEPSt13_Rb_tree_nodeIS2_E(int32_t a1, int32_t a2) {
    int32_t v1 = g2; // 0x804956c
    g2 = &v1;
    int32_t result; // 0x80495c1
    if (a2 == 0) {
        // 0x804956c
        result = g1;
        // branch -> 0x80495bf
    } else {
        int32_t v2; // bp-28
        *(int32_t *)((int32_t)&v2 - 16) = a2;
        int32_t v3 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_rightEPSt18_Rb_tree_node_base(v1); // 0x804957e
        g1 = v3;
        *(int32_t *)(g8 + 4) = v3;
        *(int32_t *)g8 = a1;
        _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_M_eraseEPSt13_Rb_tree_nodeIS2_E(v1, 0);
        *(int32_t *)g8 = a2;
        int32_t v4 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE7_S_leftEPSt18_Rb_tree_node_base(v1); // 0x804959b
        *(int32_t *)(g8 + 4) = a2;
        *(int32_t *)g8 = a1;
        _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE12_M_drop_nodeEPSt13_Rb_tree_nodeIS2_E(v4);
        while (v4 != 0) {
            // 0x8049578
            a2 = v4;
            *(int32_t *)g8 = a2;
            v3 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_rightEPSt18_Rb_tree_node_base(v1);
            g1 = v3;
            *(int32_t *)(g8 + 4) = v3;
            *(int32_t *)g8 = a1;
            _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_M_eraseEPSt13_Rb_tree_nodeIS2_E(v1, 0);
            *(int32_t *)g8 = a2;
            v4 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE7_S_leftEPSt18_Rb_tree_node_base(v1);
            *(int32_t *)(g8 + 4) = a2;
            *(int32_t *)g8 = a1;
            _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE12_M_drop_nodeEPSt13_Rb_tree_nodeIS2_E(v4);
            // continue -> 0x8049578
        }
        // 0x8049572
        result = 0;
        // branch -> 0x80495bf
    }
    // 0x80495bf
    g2 = v1;
    return result;
}

// Address range: 0x80495c2 - 0x80495cd
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_begin()
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_M_beginEv(int32_t a1) {
    // 0x80495c2
    return *(int32_t *)(a1 + 8);
}

// Address range: 0x80495ce - 0x804961f
// Demangled:     std::map<char, int, std::less<char>, std::allocator<std::pair<char const, int> > >::lower_bound(char const &)
int32_t _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEE11lower_boundERS3_(int32_t a1, int32_t a2, int32_t a3) {
    // 0x80495ce
    _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11lower_boundERS1_(a1, a2, a3);
    int32_t result; // 0x804961c
    result = a1;
    // 0x804961b
    return result;
}

// Address range: 0x8049620 - 0x8049668
// Demangled:     std::map<char, int, std::less<char>, std::allocator<std::pair<char const, int> > >::end()
int32_t _ZNSt3mapIciSt4lessIcESaISt4pairIKciEEE3endEv(int32_t a1, int32_t a2) {
    // 0x8049620
    _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE3endEv(a1, a2);
    g4 = 0;
    int32_t result; // 0x8049665
    result = a1;
    // 0x8049664
    return result;
}

// Address range: 0x8049668 - 0x804967c
// Demangled:     std::_Rb_tree_iterator<std::pair<char const, int> >::operator==(std::_Rb_tree_iterator<std::pair<char const, int> > const &) const
int32_t _ZNKSt17_Rb_tree_iteratorISt4pairIKciEEeqERKS3_(int32_t * a1, int32_t a2) {
    int32_t v1 = *(int32_t *)a2; // 0x8049673
    return (int32_t)(*a1 == v1) | v1 & -256;
}

// Address range: 0x804967c - 0x80496c4
// Demangled:     std::map<char, int, std::less<char>, std::allocator<std::pair<char const, int> > >::key_comp() const
int32_t _ZNKSt3mapIciSt4lessIcESaISt4pairIKciEEE8key_compEv(int32_t a1, int32_t a2) {
    // 0x804967c
    _ZNKSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8key_compEv(a1, a2);
    g4 = 0;
    int32_t result; // 0x80496c1
    result = a1;
    // 0x80496c0
    return result;
}

// Address range: 0x80496c4 - 0x80496dd
// Demangled:     std::_Rb_tree_iterator<std::pair<char const, int> >::operator*() const
int32_t _ZNKSt17_Rb_tree_iteratorISt4pairIKciEEdeEv(int32_t * a1) {
    // 0x80496c4
    return _ZNSt13_Rb_tree_nodeISt4pairIKciEE9_M_valptrEv(*a1);
}

// Address range: 0x80496de - 0x80496f4
// Demangled:     std::less<char>::operator()(char const &, char const &) const
int32_t _ZNKSt4lessIcEclERKcS2_(char * a1, int32_t a2, int32_t a3) {
    char v1 = *a1; // 0x80496e4
    char v2 = *(char *)a2; // 0x80496ea
    char v3 = v1 - v2; // 0x80496ed
    return v3 < 0 != ((v3 ^ v1) & (v2 ^ v1)) < 0;
}

// Address range: 0x80496f4 - 0x80496fc
// Demangled:     std::remove_reference<char &>::type && std::move<char &>(char & &&)
int32_t _ZSt4moveIRcEONSt16remove_referenceIT_E4typeEOS2_(void) {
    // 0x80496f4
    int32_t result;
    return result;
}

// Address range: 0x80496fc - 0x8049718
int32_t _ZNSt5tupleIJOcEEC1EOS1_(int32_t a1, int32_t a2) {
    // 0x80496fc
    return _ZNSt11_Tuple_implILj0EJOcEEC1EOS1_(a1, a2);
}

// Address range: 0x8049718 - 0x8049742
int32_t _ZSt16forward_as_tupleIJcEESt5tupleIJDpOT_EES3_(void) {
    // 0x8049718
    int32_t result;
    int32_t v1;
    _ZNSt5tupleIJOcEEC1IJcELb1EEEDpOT_(result, _ZSt7forwardIcEOT_RNSt16remove_referenceIS0_E4typeE(v1));
    return result;
}

// Address range: 0x8049742 - 0x8049752
// Demangled:     std::_Rb_tree_const_iterator<std::pair<char const, int> >::_Rb_tree_const_iterator(std::_Rb_tree_iterator<std::pair<char const, int> > const &)
int32_t _ZNSt23_Rb_tree_const_iteratorISt4pairIKciEEC1ERKSt17_Rb_tree_iteratorIS2_E(void) {
    // 0x8049742
    int32_t v1;
    int32_t v2;
    *(int32_t *)v1 = *(int32_t *)v2;
    return 0;
}

// Address range: 0x8049752 - 0x8049881
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE22_M_emplace_hint_uniqueIJRKSt21piecewise_construct_tSt5tupleIJOcEESD_IJEEEEESt17_Rb_tree_iteratorIS2_ESt23_Rb_tree_const_iteratorIS2_EDpOT_(void) {
    int32_t v1 = g7; // 0x8049755
    int32_t v2;
    g7 = _ZSt7forwardISt5tupleIJEEEOT_RNSt16remove_referenceIS2_E4typeE(v2);
    int32_t v3;
    g3 = _ZSt7forwardISt5tupleIJOcEEEOT_RNSt16remove_referenceIS3_E4typeE(v3);
    int32_t v4;
    int32_t v5;
    int32_t v6 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE14_M_create_nodeIJRKSt21piecewise_construct_tSt5tupleIJOcEESD_IJEEEEEPSt13_Rb_tree_nodeIS2_EDpOT_(v5, _ZSt7forwardIRKSt21piecewise_construct_tEOT_RNSt16remove_referenceIS3_E4typeE(v4), g3, g7); // 0x80497b7
    int32_t v7 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt13_Rb_tree_nodeIS2_E(v6); // 0x80497c8
    int32_t v8; // bp-24
    int32_t v9;
    _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE29_M_get_insert_hint_unique_posESt23_Rb_tree_const_iteratorIS2_ERS1_((int32_t)&v8, v5, v9, v7);
    int32_t v10;
    int32_t v11;
    if (v10 == 0) {
        // 0x804980b
        _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE12_M_drop_nodeEPSt13_Rb_tree_nodeIS2_E(v5);
        _ZNSt17_Rb_tree_iteratorISt4pairIKciEEC1EPSt18_Rb_tree_node_base((int32_t *)v11, v8);
        // branch -> 0x8049864
    } else {
        // 0x80497ec
        _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE14_M_insert_nodeEPSt18_Rb_tree_node_baseSA_PSt13_Rb_tree_nodeIS2_E(v11, v5, v8, v10, v6);
        // branch -> 0x8049864
    }
    // 0x8049864
    int32_t result; // 0x804987e
    result = v11;
    // 0x8049878
    g7 = v1;
    return result;
}

// Address range: 0x8049882 - 0x8049888
// Demangled:     __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<char const, int> > >::new_allocator()
int32_t _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEEC1Ev(int32_t a1) {
    // 0x8049882
    return g1;
}

// Address range: 0x8049888 - 0x8049893
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_S_right(std::_Rb_tree_node_base *)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_rightEPSt18_Rb_tree_node_base(int32_t a1) {
    // 0x8049888
    return *(int32_t *)(a1 + 12);
}

// Address range: 0x8049893 - 0x804989e
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_S_left(std::_Rb_tree_node_base *)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE7_S_leftEPSt18_Rb_tree_node_base(int32_t a1) {
    // 0x8049893
    return *(int32_t *)(a1 + 8);
}

// Address range: 0x804989e - 0x80498c9
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_drop_node(std::_Rb_tree_node<std::pair<char const, int> > *)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE12_M_drop_nodeEPSt13_Rb_tree_nodeIS2_E(int32_t a1) {
    // 0x804989e
    int32_t v1;
    _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE15_M_destroy_nodeEPSt13_Rb_tree_nodeIS2_E(a1, v1);
    return _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11_M_put_nodeEPSt13_Rb_tree_nodeIS2_E(a1, v1);
}

// Address range: 0x80498ca - 0x8049940
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::lower_bound(char const &)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11lower_boundERS1_(int32_t a1, int32_t a2, int32_t a3) {
    // 0x80498ca
    g3 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_M_endEv(a2);
    int32_t v1 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_M_beginEv(a2); // 0x8049904
    _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE14_M_lower_boundEPSt13_Rb_tree_nodeIS2_EPSt18_Rb_tree_node_baseRS1_(a1, a2, v1, g3, a3);
    int32_t result; // 0x804993d
    result = a1;
    // 0x8049939
    return result;
}

// Address range: 0x8049940 - 0x8049962
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::end()
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE3endEv(int32_t result, int32_t a2) {
    // 0x8049940
    _ZNSt17_Rb_tree_iteratorISt4pairIKciEEC1EPSt18_Rb_tree_node_base((int32_t *)result, a2 + 4);
    return result;
}

// Address range: 0x8049962 - 0x804996d
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::key_comp() const
int32_t _ZNKSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8key_compEv(int32_t result, int32_t a2) {
    // 0x8049962
    return result;
}

// Address range: 0x804996e - 0x8049988
// Demangled:     std::_Rb_tree_node<std::pair<char const, int> >::_M_valptr()
int32_t _ZNSt13_Rb_tree_nodeISt4pairIKciEE9_M_valptrEv(int32_t a1) {
    // 0x804996e
    return _ZN9__gnu_cxx16__aligned_membufISt4pairIKciEE6_M_ptrEv(a1 + 16);
}

// Address range: 0x8049988 - 0x8049990
// Demangled:     char && std::forward<char>(std::remove_reference<char>::type &)
int32_t _ZSt7forwardIcEOT_RNSt16remove_referenceIS0_E4typeE(int32_t result) {
    // 0x8049988
    return result;
}

// Address range: 0x8049990 - 0x80499bb
int32_t _ZNSt5tupleIJOcEEC1IJcELb1EEEDpOT_(int32_t a1, int32_t a2) {
    int32_t v1 = g3; // 0x8049993
    g3 = a1;
    int32_t v2 = g3; // 0x80499ac
    g3 = v1;
    return _ZNSt11_Tuple_implILj0EJOcEEC1IcEEOT_(v2, _ZSt7forwardIcEOT_RNSt16remove_referenceIS0_E4typeE(a2));
}

// Address range: 0x80499bc - 0x80499f3
int32_t _ZNSt11_Tuple_implILj0EJOcEEC1EOS1_(int32_t a1, int32_t a2) {
    // 0x80499bc
    return _ZNSt10_Head_baseILj0EOcLb0EEC1IcEEOT_((int32_t *)a1, _ZSt7forwardIOcEOT_RNSt16remove_referenceIS1_E4typeE(_ZNSt11_Tuple_implILj0EJOcEE7_M_headERS1_(a2)));
}

// Address range: 0x80499f3 - 0x80499fb
// Demangled:     std::piecewise_construct_t const & && std::forward<std::piecewise_construct_t const &>(std::remove_reference<std::piecewise_construct_t const &>::type &)
int32_t _ZSt7forwardIRKSt21piecewise_construct_tEOT_RNSt16remove_referenceIS3_E4typeE(int32_t result) {
    // 0x80499f3
    return result;
}

// Address range: 0x80499fb - 0x8049a03
int32_t _ZSt7forwardISt5tupleIJOcEEEOT_RNSt16remove_referenceIS3_E4typeE(int32_t result) {
    // 0x80499fb
    return result;
}

// Address range: 0x8049a03 - 0x8049a0b
int32_t _ZSt7forwardISt5tupleIJEEEOT_RNSt16remove_referenceIS2_E4typeE(int32_t result) {
    // 0x8049a03
    return result;
}

// Address range: 0x8049a0c - 0x8049a71
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE14_M_create_nodeIJRKSt21piecewise_construct_tSt5tupleIJOcEESD_IJEEEEEPSt13_Rb_tree_nodeIS2_EDpOT_(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t v1 = g3; // 0x8049a10
    int32_t result = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11_M_get_nodeEv(a1); // 0x8049a1a
    g7 = _ZSt7forwardISt5tupleIJEEEOT_RNSt16remove_referenceIS2_E4typeE(a4);
    g3 = _ZSt7forwardISt5tupleIJOcEEEOT_RNSt16remove_referenceIS3_E4typeE(a3);
    _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE17_M_construct_nodeIJRKSt21piecewise_construct_tSt5tupleIJOcEESD_IJEEEEEvPSt13_Rb_tree_nodeIS2_EDpOT_(a1, result, _ZSt7forwardIRKSt21piecewise_construct_tEOT_RNSt16remove_referenceIS3_E4typeE(a2), g3, g7);
    g3 = v1;
    return result;
}

// Address range: 0x8049a72 - 0x8049dd0
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_get_insert_hint_unique_pos(std::_Rb_tree_const_iterator<std::pair<char const, int> >, char const &)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE29_M_get_insert_hint_unique_posESt23_Rb_tree_const_iteratorIS2_ERS1_(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x8049a72
    int32_t v1; // bp-28
    int32_t v2 = &v1; // 0x8049a96
    int32_t v3 = 0; // bp+12
    _ZNKSt23_Rb_tree_const_iteratorISt4pairIKciEE13_M_const_castEv(v2, &v3);
    g3 = v1;
    int32_t v4; // bp-20
    int32_t result; // 0x8049dcd
    int32_t * v5;
    if (g3 == _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_M_endEv(a2)) {
        // 0x8049ac7
        if (_ZNKSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE4sizeEv(a2) != 0) {
            // 0x8049ad9
            g3 = a2;
            int32_t v6 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE12_M_rightmostEv(a2); // 0x8049ae2
            int32_t v7 = *(int32_t *)v6; // 0x8049aea
            int32_t v8 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt18_Rb_tree_node_base(v7); // 0x8049af0
            if ((char)_ZNKSt4lessIcEclERKcS2_((char *)g3, v8, a3) != 0) {
                int32_t v9 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE12_M_rightmostEv(a2); // 0x8049b22
                v4 = 0;
                _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_Lb1EEERKS1_OT_((int32_t *)a1, (int32_t)&v4, v9);
                // branch -> 0x8049db5
                result = a1;
                // 0x8049dc9
                return result;
            }
        }
        // 0x8049b49
        _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE24_M_get_insert_unique_posERS1_(a1, a2, a3);
        // branch -> 0x8049db5
        result = a1;
        // 0x8049dc9
        return result;
    }
    int32_t v10 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt18_Rb_tree_node_base(v1); // 0x8049b6d
    int32_t v11; // bp-24
    if ((char)_ZNKSt4lessIcEclERKcS2_((char *)a2, a3, v10) != 0) {
        v11 = v1;
        int32_t v12 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11_M_leftmostEv(a2); // 0x8049b9c
        if (v1 == *(int32_t *)v12) {
            int32_t v13 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11_M_leftmostEv(a2); // 0x8049bb5
            _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_S4_Lb1EEEOT_OT0_((int32_t *)a1, _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11_M_leftmostEv(a2), v13);
            // branch -> 0x8049db5
            result = a1;
            // 0x8049dc9
            return result;
        }
        // 0x8049be2
        g3 = a2;
        int32_t v14 = &v11; // 0x8049be8
        int32_t v15 = *(int32_t *)_ZNSt17_Rb_tree_iteratorISt4pairIKciEEmmEv(&v11); // 0x8049bf4
        int32_t v16 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt18_Rb_tree_node_base(v15); // 0x8049bfa
        if ((char)_ZNKSt4lessIcEclERKcS2_((char *)g3, v16, a3) == 0) {
            // 0x8049c6b
            _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE24_M_get_insert_unique_posERS1_(a1, a2, a3);
            // branch -> 0x8049db5
            result = a1;
            // 0x8049dc9
            return result;
        }
        // 0x8049c16
        if (_ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_rightEPSt18_Rb_tree_node_base(v11) != 0) {
            // 0x8049c50
            _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_S4_Lb1EEEOT_OT0_((int32_t *)a1, v2, v2);
            // branch -> 0x8049db5
        } else {
            // 0x8049c2e
            v4 = 0;
            _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_Lb1EEERKS1_OT_((int32_t *)a1, (int32_t)&v4, v14);
            // branch -> 0x8049db5
        }
        result = a1;
        // 0x8049dc9
        return result;
    }
    int32_t v17 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt18_Rb_tree_node_base(v1); // 0x8049c8f
    if ((char)_ZNKSt4lessIcEclERKcS2_((char *)a2, v17, a3) == 0) {
        // 0x8049d98
        v4 = 0;
        _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_Lb1EEEOT_RKS1_((int32_t *)a1, v2, (int32_t)&v4);
        // branch -> 0x8049db5
        result = a1;
        // 0x8049dc9
        return result;
    }
    int32_t v18 = v1; // 0x8049caf
    v11 = v18;
    int32_t v19 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE12_M_rightmostEv(a2); // 0x8049cbe
    if (v18 == *(int32_t *)v19) {
        int32_t v20 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE12_M_rightmostEv(a2); // 0x8049cd7
        v4 = 0;
        _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_Lb1EEERKS1_OT_((int32_t *)a1, (int32_t)&v4, v20);
        // branch -> 0x8049db5
        result = a1;
        // 0x8049dc9
        return result;
    }
    // 0x8049cfe
    g3 = a2;
    int32_t v21 = &v11; // 0x8049d04
    int32_t v22 = *(int32_t *)_ZNSt17_Rb_tree_iteratorISt4pairIKciEEppEv(&v11); // 0x8049d10
    int32_t v23 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt18_Rb_tree_node_base(v22); // 0x8049d16
    if ((char)_ZNKSt4lessIcEclERKcS2_((char *)g3, a3, v23) == 0) {
        // 0x8049d81
        _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE24_M_get_insert_unique_posERS1_(a1, a2, a3);
        // branch -> 0x8049db5
        result = a1;
        // 0x8049dc9
        return result;
    }
    // 0x8049d32
    if (_ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_rightEPSt18_Rb_tree_node_base(v1) != 0) {
        // 0x8049d69
        _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_S4_Lb1EEEOT_OT0_((int32_t *)a1, v21, v21);
        // branch -> 0x8049db5
    } else {
        // 0x8049d4a
        v4 = 0;
        _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_Lb1EEERKS1_OT_((int32_t *)a1, (int32_t)&v4, v2);
        // branch -> 0x8049db5
    }
    result = a1;
    // 0x8049dc9
    return result;
}

// Address range: 0x8049dd0 - 0x8049e19
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_S_key(std::_Rb_tree_node<std::pair<char const, int> > const *)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt13_Rb_tree_nodeIS2_E(int32_t a1) {
    int32_t v1 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_valueEPKSt13_Rb_tree_nodeIS2_E(a1); // 0x8049ded
    int32_t v2; // bp-17
    int32_t v3 = _ZNKSt10_Select1stISt4pairIKciEEclERKS2_((int32_t)&v2, v1); // 0x8049dfd
    int32_t result; // 0x8049e18
    result = v3;
    // 0x8049e17
    return result;
}

// Address range: 0x8049e1a - 0x8049ec3
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_insert_node(std::_Rb_tree_node_base *, std::_Rb_tree_node_base *, std::_Rb_tree_node<std::pair<char const, int> > *)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE14_M_insert_nodeEPSt18_Rb_tree_node_baseSA_PSt13_Rb_tree_nodeIS2_E(int32_t result, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    // 0x8049e1a
    int32_t * v1; // 0x8049e9a
    if (a3 != 0) {
        // 0x8049e1a
        // branch -> 0x8049e7a
        // 0x8049e7a
        function_8049040(1, a5, a4, a2 + 4);
        v1 = (int32_t *)(a2 + 20);
        *v1 = *v1 + 1;
        _ZNSt17_Rb_tree_iteratorISt4pairIKciEEC1EPSt18_Rb_tree_node_base((int32_t *)result, a5);
        return result;
    }
    // 0x8049e28
    int32_t v2;
    if (_ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_M_endEv(a2) != a4) {
        int32_t v3 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt18_Rb_tree_node_base(a4); // 0x8049e44
        int32_t v4 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt13_Rb_tree_nodeIS2_E(a5); // 0x8049e54
        v2 = (char)_ZNKSt4lessIcEclERKcS2_((char *)a2, v4, v3) != 0;
        // branch -> 0x8049e7a
    } else {
        v2 = 1;
    }
    // 0x8049e7a
    function_8049040(v2, a5, a4, a2 + 4);
    v1 = (int32_t *)(a2 + 20);
    *v1 = *v1 + 1;
    _ZNSt17_Rb_tree_iteratorISt4pairIKciEEC1EPSt18_Rb_tree_node_base((int32_t *)result, a5);
    return result;
}

// Address range: 0x8049ec4 - 0x8049ed2
// Demangled:     std::_Rb_tree_iterator<std::pair<char const, int> >::_Rb_tree_iterator(std::_Rb_tree_node_base *)
int32_t _ZNSt17_Rb_tree_iteratorISt4pairIKciEEC1EPSt18_Rb_tree_node_base(int32_t * a1, int32_t a2) {
    // 0x8049ec4
    *a1 = a2;
    return (int32_t)a1;
}

// Address range: 0x8049ed2 - 0x8049f0a
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_destroy_node(std::_Rb_tree_node<std::pair<char const, int> > *)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE15_M_destroy_nodeEPSt13_Rb_tree_nodeIS2_E(int32_t a1, int32_t a2) {
    int32_t v1 = _ZNSt13_Rb_tree_nodeISt4pairIKciEE9_M_valptrEv(a2); // 0x8049edf
    int32_t v2 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE21_M_get_Node_allocatorEv(a1); // 0x8049eef
    g1 = v2;
    return _ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKciEEEE7destroyIS3_EEvRS5_PT_(v2, v1);
}

// Address range: 0x8049f0a - 0x8049f32
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_put_node(std::_Rb_tree_node<std::pair<char const, int> > *)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11_M_put_nodeEPSt13_Rb_tree_nodeIS2_E(int32_t a1, int32_t a2) {
    // 0x8049f0a
    return _ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKciEEEE10deallocateERS5_PS4_j(_ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE21_M_get_Node_allocatorEv(a1), a2, 1);
}

// Address range: 0x8049f32 - 0x8049f3d
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_end()
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_M_endEv(int32_t a1) {
    // 0x8049f32
    return a1 + 4;
}

// Address range: 0x8049f3e - 0x8049fba
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_lower_bound(std::_Rb_tree_node<std::pair<char const, int> > *, std::_Rb_tree_node_base *, char const &)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE14_M_lower_boundEPSt13_Rb_tree_nodeIS2_EPSt18_Rb_tree_node_baseRS1_(int32_t result, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    int32_t v1 = g2; // bp-4
    g2 = &v1;
    int32_t v2; // bp-12
    int32_t v3 = &v2; // 0x8049f42
    if (a3 == 0) {
        // 0x8049f9f
        *(int32_t *)(v3 - 12) = a4;
        *(int32_t *)(v3 - 16) = result;
        _ZNSt17_Rb_tree_iteratorISt4pairIKciEEC1EPSt18_Rb_tree_node_base(NULL, a4);
        g2 = v1;
        return result;
    }
    // branch -> 0x8049f4b
  lab_0x8049f4b:
    while (true) {
        int32_t v4 = v3; // 0x8049f4e
        int32_t v5 = a3;
        // branch -> 0x8049f4b
        while (true) {
            // 0x8049f4b
            *(int32_t *)(v4 - 16) = v5;
            int32_t v6 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt13_Rb_tree_nodeIS2_E(g3); // eax
            *(int32_t *)(g8 + 8) = a5;
            *(int32_t *)(g8 + 4) = v6;
            *(int32_t *)g8 = a2;
            if ((char)(_ZNKSt4lessIcEclERKcS2_((char *)g3, v1, 0) ^ 1) == 0) {
                // 0x8049f8c
                *(int32_t *)g8 = v5;
                int32_t v7 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_rightEPSt18_Rb_tree_node_base(v5); // 0x8049f92
                int32_t v8 = g8 + 16; // 0x8049f97
                if (v7 == 0) {
                    v3 = v8;
                    // break -> 0x8049f9f
                    break;
                }
                v4 = v8;
                v5 = v7;
                // continue -> 0x8049f4b
                continue;
            } else {
                // 0x8049f73
                *(int32_t *)g8 = v5;
                int32_t v9 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE7_S_leftEPSt18_Rb_tree_node_base(v5); // 0x8049f7f
                int32_t v10 = g8 + 16; // 0x8049f84
                if (v9 == 0) {
                    v3 = v10;
                    a4 = v5;
                    // break (via goto) -> 0x8049f9f
                    goto lab_0x8049f9f;
                }
                v3 = v10;
                a3 = v9;
                a4 = v5;
                // continue (via goto) -> 0x8049f4b
                goto lab_0x8049f4b;
            }
            // 0x8049f9f
            *(int32_t *)(v3 - 12) = a4;
            *(int32_t *)(v3 - 16) = result;
            _ZNSt17_Rb_tree_iteratorISt4pairIKciEEC1EPSt18_Rb_tree_node_base(NULL, a4);
            v6 = result;
            int32_t v11 = v1; // 0x8049fb6
            g2 = v11;
            return result;
        }
      lab_0x8049f9f:
        // 0x8049f9f
        *(int32_t *)(v3 - 12) = a4;
        *(int32_t *)(v3 - 16) = result;
        _ZNSt17_Rb_tree_iteratorISt4pairIKciEEC1EPSt18_Rb_tree_node_base(NULL, a4);
        g2 = v1;
        return result;
    }
}

// Address range: 0x8049fba - 0x8049fd0
// Demangled:     __gnu_cxx::__aligned_membuf<std::pair<char const, int> >::_M_ptr()
int32_t _ZN9__gnu_cxx16__aligned_membufISt4pairIKciEE6_M_ptrEv(int32_t a1) {
    // 0x8049fba
    return _ZN9__gnu_cxx16__aligned_membufISt4pairIKciEE7_M_addrEv(a1);
}

// Address range: 0x8049fd0 - 0x8049ffb
int32_t _ZNSt11_Tuple_implILj0EJOcEEC1IcEEOT_(int32_t a1, int32_t a2) {
    // 0x8049fd0
    return _ZNSt10_Head_baseILj0EOcLb0EEC1IcEEOT_((int32_t *)a1, _ZSt7forwardIcEOT_RNSt16remove_referenceIS0_E4typeE(a2));
}

// Address range: 0x8049ffb - 0x804a012
int32_t _ZNSt11_Tuple_implILj0EJOcEE7_M_headERS1_(int32_t a1) {
    // 0x8049ffb
    return _ZNSt10_Head_baseILj0EOcLb0EE7_M_headERS1_((int32_t *)a1);
}

// Address range: 0x804a012 - 0x804a01a
// Demangled:     char && && std::forward<char &&>(std::remove_reference<char &&>::type &)
int32_t _ZSt7forwardIOcEOT_RNSt16remove_referenceIS1_E4typeE(int32_t result) {
    // 0x804a012
    return result;
}

// Address range: 0x804a01a - 0x804a038
// Demangled:     std::_Head_base<, char &&, false>::_Head_base<char>(char &&)
int32_t _ZNSt10_Head_baseILj0EOcLb0EEC1IcEEOT_(int32_t * a1, int32_t a2) {
    int32_t v1 = _ZSt7forwardIcEOT_RNSt16remove_referenceIS0_E4typeE(a2); // 0x804a026
    g6 = v1;
    *a1 = v1;
    return (int32_t)a1;
}

// Address range: 0x804a038 - 0x804a05c
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_get_node()
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11_M_get_nodeEv(int32_t a1) {
    // 0x804a038
    return _ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKciEEEE8allocateERS5_j(_ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE21_M_get_Node_allocatorEv(a1), 1);
}

// Address range: 0x804a05c - 0x804a115
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE17_M_construct_nodeIJRKSt21piecewise_construct_tSt5tupleIJOcEESD_IJEEEEEvPSt13_Rb_tree_nodeIS2_EDpOT_(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    int32_t v1 = g5; // 0x804a05f
    _ZnwjPv(24, a2);
    int32_t v2 = _ZSt7forwardISt5tupleIJEEEOT_RNSt16remove_referenceIS2_E4typeE(a5); // 0x804a07c
    g5 = _ZSt7forwardISt5tupleIJOcEEEOT_RNSt16remove_referenceIS3_E4typeE(a4);
    g7 = _ZSt7forwardIRKSt21piecewise_construct_tEOT_RNSt16remove_referenceIS3_E4typeE(a3);
    g3 = _ZNSt13_Rb_tree_nodeISt4pairIKciEE9_M_valptrEv(a2);
    int32_t v3 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE21_M_get_Node_allocatorEv(a1); // 0x804a0bd
    int32_t v4 = g5; // 0x804a0cb
    g5 = v1;
    return _ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKciEEEE9constructIS3_JRKSt21piecewise_construct_tSt5tupleIJOcEESB_IJEEEEEvRS5_PT_DpOT0_(v3, g3, g7, v4, v2);
}

// Address range: 0x804a116 - 0x804a137
// Demangled:     std::_Rb_tree_const_iterator<std::pair<char const, int> >::_M_const_cast() const
int32_t _ZNKSt23_Rb_tree_const_iteratorISt4pairIKciEE13_M_const_castEv(int32_t result, int32_t * a2) {
    // 0x804a116
    _ZNSt17_Rb_tree_iteratorISt4pairIKciEEC1EPSt18_Rb_tree_node_base((int32_t *)result, *a2);
    return result;
}

// Address range: 0x804a138 - 0x804a143
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::size() const
int32_t _ZNKSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE4sizeEv(int32_t a1) {
    // 0x804a138
    return *(int32_t *)(a1 + 20);
}

// Address range: 0x804a144 - 0x804a14f
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_rightmost()
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE12_M_rightmostEv(int32_t a1) {
    // 0x804a144
    return a1 + 16;
}

// Address range: 0x804a14f - 0x804a198
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_S_key(std::_Rb_tree_node_base const *)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt18_Rb_tree_node_base(int32_t a1) {
    int32_t v1 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_valueEPKSt18_Rb_tree_node_base(a1); // 0x804a16c
    int32_t v2; // bp-17
    int32_t v3 = _ZNKSt10_Select1stISt4pairIKciEEclERKS2_((int32_t)&v2, v1); // 0x804a17c
    int32_t result; // 0x804a197
    result = v3;
    // 0x804a196
    return result;
}

// Address range: 0x804a198 - 0x804a1c1
// Demangled:     std::pair<std::_Rb_tree_node_base * &, true>::pair(std::_Rb_tree_node_base * const &, std::_Rb_tree_node_base * & &&)
int32_t _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_Lb1EEERKS1_OT_(int32_t * a1, int32_t a2, int32_t a3) {
    int32_t result = (int32_t)a1;
    *a1 = *(int32_t *)a2;
    int32_t v1 = _ZSt7forwardIRPSt18_Rb_tree_node_baseEOT_RNSt16remove_referenceIS3_E4typeE(a3); // 0x804a1ae
    *(int32_t *)(result + 4) = *(int32_t *)v1;
    return result;
}

// Address range: 0x804a1c2 - 0x804a348
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_get_insert_unique_pos(char const &)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE24_M_get_insert_unique_posERS1_(int32_t a1, int32_t a2, int32_t a3) {
    // 0x804a1c2
    int32_t v1; // bp-60
    int32_t v2 = &v1; // 0x804a1c6
    int32_t v3 = *(int32_t *)20; // 0x804a1db
    int32_t v4 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_M_beginEv(a2); // 0x804a1ec
    int32_t v5 = v4; // bp-32
    int32_t v6 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_M_endEv(a2); // 0x804a1fd
    bool v7 = false;
    int32_t v8; // bp-20
    int32_t v9; // bp-24
    if (v4 != 0) {
        int32_t v10; // 0x804a250
        int32_t v11; // 0x804a233
        while (true) {
            // 0x804a213
            v6 = v4;
            *(int32_t *)(v2 - 16) = v4;
            int32_t v12 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt13_Rb_tree_nodeIS2_E(v6); // 0x804a223
            *(int32_t *)(g8 + 8) = v12;
            *(int32_t *)(g8 + 4) = a3;
            *(int32_t *)g8 = a2;
            v9 = 0;
            v8 = 0;
            v11 = _ZNKSt4lessIcEclERKcS2_((char *)v6, v9, v8);
            *(int32_t *)g8 = v5;
            int32_t v13 = 0x1000000 * v11 / 0x1000000; // 0x804a25c
            int32_t v14;
            if ((char)v11 == 0) {
                // 0x804a255
                v14 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_rightEPSt18_Rb_tree_node_base(v13);
                // branch -> 0x804a264
            } else {
                // 0x804a244
                v14 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE7_S_leftEPSt18_Rb_tree_node_base(v13);
                // branch -> 0x804a264
            }
            // 0x804a264
            v10 = g8 + 16;
            v5 = v14;
            if (v14 == 0) {
                // break -> 0x804a20c
                break;
            }
            v2 = v10;
            v4 = v14;
            // continue -> 0x804a213
        }
        // 0x804a20c
        v2 = v10;
        v7 = (char)v11 == 0;
        // branch -> 0x804a269
    }
    // 0x804a269
    *(int32_t *)(v2 - 12) = v6;
    int32_t v15 = &v9; // 0x804a270
    *(int32_t *)(v2 - 16) = v15;
    _ZNSt17_Rb_tree_iteratorISt4pairIKciEEC1EPSt18_Rb_tree_node_base((int32_t *)v5, v6);
    int32_t v16; // 0x804a2e1
    int32_t v17; // 0x804a2f1
    int32_t result; // 0x804a345
    int32_t v18; // 0x804a2dc
    int32_t v19; // 0x804a2ec
    int32_t * v20;
    if (v7) {
        // 0x804a2d2
        *(int32_t *)g8 = v9;
        v18 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt18_Rb_tree_node_base(v5);
        v16 = g8;
        *(int32_t *)(v16 + 8) = a3;
        *(int32_t *)(v16 + 4) = v18;
        *(int32_t *)v16 = a2;
        v19 = _ZNKSt4lessIcEclERKcS2_((char *)v5, v6, v9);
        v17 = g8;
        if ((char)v19 == 0) {
            // 0x804a310
            v8 = 0;
            *(int32_t *)(v17 + 8) = (int32_t)&v8;
            *(int32_t *)(v17 + 4) = v15;
            *(int32_t *)v17 = a1;
            _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_Lb1EEEOT_RKS1_((int32_t *)v8, v3, (int32_t)&v20);
            // branch -> 0x804a32d
        } else {
            // 0x804a2f8
            *(int32_t *)(v17 + 8) = (int32_t)&v6;
            *(int32_t *)(v17 + 4) = (int32_t)&v5;
            *(int32_t *)v17 = a1;
            _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRPSt13_Rb_tree_nodeIS_IKciEERS1_Lb1EEEOT_OT0_();
            // branch -> 0x804a32d
        }
        result = a1;
        // 0x804a341
        return result;
    }
    int32_t v21 = &v8; // 0x804a282
    *(int32_t *)(g8 + 4) = a2;
    *(int32_t *)g8 = v21;
    _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE5beginEv();
    *(int32_t *)g8 = v21;
    *(int32_t *)(g8 - 4) = v15;
    if ((char)_ZNKSt17_Rb_tree_iteratorISt4pairIKciEEeqERKS3_((int32_t *)v5, v6) != 0) {
        // 0x804a2ab
        *(int32_t *)(g8 + 8) = (int32_t)&v6;
        *(int32_t *)(g8 + 4) = (int32_t)&v5;
        *(int32_t *)g8 = a1;
        _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRPSt13_Rb_tree_nodeIS_IKciEERS1_Lb1EEEOT_OT0_();
        // branch -> 0x804a32d
        result = a1;
        // 0x804a341
        return result;
    }
    // 0x804a2c3
    *(int32_t *)g8 = v15;
    _ZNSt17_Rb_tree_iteratorISt4pairIKciEEmmEv((int32_t *)v5);
    // branch -> 0x804a2d2
    // 0x804a2d2
    *(int32_t *)g8 = v9;
    v18 = _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE6_S_keyEPKSt18_Rb_tree_node_base(v5);
    v16 = g8;
    *(int32_t *)(v16 + 8) = a3;
    *(int32_t *)(v16 + 4) = v18;
    *(int32_t *)v16 = a2;
    v19 = _ZNKSt4lessIcEclERKcS2_((char *)v5, v6, v9);
    v17 = g8;
    if ((char)v19 == 0) {
        // 0x804a310
        v8 = 0;
        *(int32_t *)(v17 + 8) = (int32_t)&v8;
        *(int32_t *)(v17 + 4) = v15;
        *(int32_t *)v17 = a1;
        _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_Lb1EEEOT_RKS1_((int32_t *)v8, v3, (int32_t)&v20);
        // branch -> 0x804a32d
    } else {
        // 0x804a2f8
        *(int32_t *)(v17 + 8) = (int32_t)&v6;
        *(int32_t *)(v17 + 4) = (int32_t)&v5;
        *(int32_t *)v17 = a1;
        _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRPSt13_Rb_tree_nodeIS_IKciEERS1_Lb1EEEOT_OT0_();
        // branch -> 0x804a32d
    }
    result = a1;
    // 0x804a341
    return result;
}

// Address range: 0x804a348 - 0x804a353
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_leftmost()
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE11_M_leftmostEv(int32_t a1) {
    // 0x804a348
    return a1 + 12;
}

// Address range: 0x804a354 - 0x804a388
int32_t _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_S4_Lb1EEEOT_OT0_(int32_t * a1, int32_t a2, int32_t a3) {
    int32_t result = (int32_t)a1;
    *a1 = *(int32_t *)_ZSt7forwardIRPSt18_Rb_tree_node_baseEOT_RNSt16remove_referenceIS3_E4typeE(a2);
    int32_t v1 = _ZSt7forwardIRPSt18_Rb_tree_node_baseEOT_RNSt16remove_referenceIS3_E4typeE(a3); // 0x804a375
    *(int32_t *)(result + 4) = *(int32_t *)v1;
    return result;
}

// Address range: 0x804a388 - 0x804a3ab
// Demangled:     std::_Rb_tree_iterator<std::pair<char const, int> >::operator--()
int32_t _ZNSt17_Rb_tree_iteratorISt4pairIKciEEmmEv(int32_t * a1) {
    // 0x804a388
    *a1 = function_80490a0(*a1);
    return (int32_t)a1;
}

// Address range: 0x804a3ac - 0x804a3cf
// Demangled:     std::_Rb_tree_iterator<std::pair<char const, int> >::operator++()
int32_t _ZNSt17_Rb_tree_iteratorISt4pairIKciEEppEv(int32_t * a1) {
    // 0x804a3ac
    *a1 = function_8049070(*a1);
    return (int32_t)a1;
}

// Address range: 0x804a3d0 - 0x804a3f9
// Demangled:     std::pair<std::_Rb_tree_node_base * &, true>::pair(std::_Rb_tree_node_base * & &&, std::_Rb_tree_node_base * const &)
int32_t _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRS1_Lb1EEEOT_RKS1_(int32_t * a1, int32_t a2, int32_t a3) {
    int32_t result = (int32_t)a1;
    *a1 = *(int32_t *)_ZSt7forwardIRPSt18_Rb_tree_node_baseEOT_RNSt16remove_referenceIS3_E4typeE(a2);
    *(int32_t *)(result + 4) = *(int32_t *)a3;
    return result;
}

// Address range: 0x804a3f9 - 0x804a40f
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_S_value(std::_Rb_tree_node<std::pair<char const, int> > const *)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_valueEPKSt13_Rb_tree_nodeIS2_E(int32_t a1) {
    // 0x804a3f9
    return _ZNKSt13_Rb_tree_nodeISt4pairIKciEE9_M_valptrEv(a1);
}

// Address range: 0x804a410 - 0x804a418
// Demangled:     std::_Select1st<std::pair<char const, int> >::operator()(std::pair<char const, int> const &) const
int32_t _ZNKSt10_Select1stISt4pairIKciEEclERKS2_(int32_t result, int32_t a2) {
    // 0x804a410
    return result;
}

// Address range: 0x804a418 - 0x804a420
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_M_get_Node_allocator()
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE21_M_get_Node_allocatorEv(int32_t result) {
    // 0x804a418
    return result;
}

// Address range: 0x804a420 - 0x804a43a
// Demangled:     void std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<char const, int> > > >::destroy<std::pair<char const, int> >(std::allocator<std::_Rb_tree_node<std::pair<char const, int> > > &, std::pair<char const, int> *)
int32_t _ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKciEEEE7destroyIS3_EEvRS5_PT_(int32_t a1, int32_t a2) {
    // 0x804a420
    return _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE7destroyIS4_EEvPT_(a1, a2);
}

// Address range: 0x804a43a - 0x804a457
// Demangled:     std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<char const, int> > > >::deallocate(std::allocator<std::_Rb_tree_node<std::pair<char const, int> > > &, std::_Rb_tree_node<std::pair<char const, int> > *, unsigned int)
int32_t _ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKciEEEE10deallocateERS5_PS4_j(int32_t a1, int32_t a2, int32_t a3) {
    // 0x804a43a
    return _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE10deallocateEPS5_j((int32_t *)a1, a2, a3);
}

// Address range: 0x804a458 - 0x804a460
// Demangled:     __gnu_cxx::__aligned_membuf<std::pair<char const, int> >::_M_addr()
int32_t _ZN9__gnu_cxx16__aligned_membufISt4pairIKciEE7_M_addrEv(int32_t result) {
    // 0x804a458
    return result;
}

// Address range: 0x804a460 - 0x804a46a
// Demangled:     std::_Head_base<, char &&, false>::_M_head(std::_Head_base<, char &&, false> &)
int32_t _ZNSt10_Head_baseILj0EOcLb0EE7_M_headERS1_(int32_t * a1) {
    // 0x804a460
    return *a1;
}

// Address range: 0x804a46a - 0x804a485
// Demangled:     std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<char const, int> > > >::allocate(std::allocator<std::_Rb_tree_node<std::pair<char const, int> > > &, unsigned int)
int32_t _ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKciEEEE8allocateERS5_j(int32_t a1, int32_t a2) {
    // 0x804a46a
    return _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE8allocateEjPKv(a1, a2, 0);
}

// Address range: 0x804a485 - 0x804a4d4
int32_t _ZNSt16allocator_traitsISaISt13_Rb_tree_nodeISt4pairIKciEEEE9constructIS3_JRKSt21piecewise_construct_tSt5tupleIJOcEESB_IJEEEEEvRS5_PT_DpOT0_(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    // 0x804a485
    g7 = _ZSt7forwardISt5tupleIJEEEOT_RNSt16remove_referenceIS2_E4typeE(a5);
    g3 = _ZSt7forwardISt5tupleIJOcEEEOT_RNSt16remove_referenceIS3_E4typeE(a4);
    int32_t v1 = _ZSt7forwardIRKSt21piecewise_construct_tEOT_RNSt16remove_referenceIS3_E4typeE(a3); // 0x804a4b0
    return _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE9constructIS4_JRKSt21piecewise_construct_tSt5tupleIJOcEESB_IJEEEEEvPT_DpOT0_(a1, a2, v1, g3, g7);
}

// Address range: 0x804a4d4 - 0x804a4ea
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::_S_value(std::_Rb_tree_node_base const *)
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE8_S_valueEPKSt18_Rb_tree_node_base(int32_t a1) {
    // 0x804a4d4
    return _ZNKSt13_Rb_tree_nodeISt4pairIKciEE9_M_valptrEv(a1);
}

// Address range: 0x804a4ea - 0x804a4f2
// Demangled:     std::_Rb_tree_node_base * & && std::forward<std::_Rb_tree_node_base * &>(std::remove_reference<std::_Rb_tree_node_base * &>::type &)
int32_t _ZSt7forwardIRPSt18_Rb_tree_node_baseEOT_RNSt16remove_referenceIS3_E4typeE(int32_t result) {
    // 0x804a4ea
    return result;
}

// Address range: 0x804a4f2 - 0x804a514
// Demangled:     std::_Rb_tree<char, std::pair<char const, int>, std::_Select1st<std::pair<char const, int> >, std::less<char>, std::allocator<std::pair<char const, int> > >::begin()
int32_t _ZNSt8_Rb_treeIcSt4pairIKciESt10_Select1stIS2_ESt4lessIcESaIS2_EE5beginEv(void) {
    // 0x804a4f2
    int32_t v1;
    int32_t v2 = *(int32_t *)(v1 + 12); // 0x804a4fb
    int32_t result;
    _ZNSt17_Rb_tree_iteratorISt4pairIKciEEC1EPSt18_Rb_tree_node_base((int32_t *)result, v2);
    return result;
}

// Address range: 0x804a514 - 0x804a548
// Demangled:     std::pair<std::_Rb_tree_node<std::pair<char const, int> > * &, std::_Rb_tree_node_base * &, true>::pair(std::_Rb_tree_node<std::pair<char const, int> > * & &&, std::_Rb_tree_node_base * & &&)
int32_t _ZNSt4pairIPSt18_Rb_tree_node_baseS1_EC1IRPSt13_Rb_tree_nodeIS_IKciEERS1_Lb1EEEOT_OT0_(void) {
    // 0x804a514
    int32_t v1;
    int32_t v2 = _ZSt7forwardIRPSt13_Rb_tree_nodeISt4pairIKciEEEOT_RNSt16remove_referenceIS7_E4typeE(v1); // 0x804a520
    int32_t v3;
    *(int32_t *)v3 = *(int32_t *)v2;
    int32_t v4;
    int32_t result = _ZSt7forwardIRPSt18_Rb_tree_node_baseEOT_RNSt16remove_referenceIS3_E4typeE(v4); // 0x804a535
    *(int32_t *)(v3 + 4) = *(int32_t *)result;
    return result;
}

// Address range: 0x804a548 - 0x804a562
// Demangled:     std::_Rb_tree_node<std::pair<char const, int> >::_M_valptr() const
int32_t _ZNKSt13_Rb_tree_nodeISt4pairIKciEE9_M_valptrEv(int32_t a1) {
    // 0x804a548
    return _ZNK9__gnu_cxx16__aligned_membufISt4pairIKciEE6_M_ptrEv(a1 + 16);
}

// Address range: 0x804a562 - 0x804a568
// Demangled:     void __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<char const, int> > >::destroy<std::pair<char const, int> >(std::pair<char const, int> *)
int32_t _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE7destroyIS4_EEvPT_(int32_t a1, int32_t a2) {
    // 0x804a562
    return g1;
}

// Address range: 0x804a568 - 0x804a57f
// Demangled:     __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<char const, int> > >::deallocate(std::_Rb_tree_node<std::pair<char const, int> > *, unsigned int)
int32_t _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE10deallocateEPS5_j(int32_t * a1, int32_t a2, int32_t a3) {
    // 0x804a568
    _ZdlPv(a1);
    int32_t * v1;
    return (int32_t)&v1;
}

// Address range: 0x804a580 - 0x804a5bd
// Demangled:     __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<char const, int> > >::allocate(unsigned int, void const *)
int32_t _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE8allocateEjPKv(int32_t a1, uint32_t a2, int32_t a3) {
    // 0x804a580
    if ((uint32_t)_ZNK9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE8max_sizeEv(a1) < a2) {
        // 0x804a59e
        function_8049050();
        // branch -> 0x804a5a3
    }
    // 0x804a5a3
    return (int32_t)_Znwj(24 * a2);
}

// Address range: 0x804a5be - 0x804a68a
int32_t _ZN9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE9constructIS4_JRKSt21piecewise_construct_tSt5tupleIJOcEESB_IJEEEEEvPT_DpOT0_(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    // 0x804a5be
    _ZSt7forwardIRKSt21piecewise_construct_tEOT_RNSt16remove_referenceIS3_E4typeE(a3);
    int32_t v1 = _ZSt7forwardISt5tupleIJOcEEEOT_RNSt16remove_referenceIS3_E4typeE(a4); // 0x804a604
    int32_t v2; // bp-36
    int32_t v3 = &v2; // 0x804a610
    _ZNSt5tupleIJOcEEC1EOS1_(v3, v1);
    _ZSt7forwardISt5tupleIJEEEOT_RNSt16remove_referenceIS2_E4typeE(a5);
    unsigned char v4;
    unsigned char v5;
    _ZNSt4pairIKciEC1IJOcEJEEESt21piecewise_construct_tSt5tupleIJDpT_EES5_IJDpT0_EE(_ZnwjPv(8, a2), (int32_t)v4, v3, (int32_t)v5);
    int32_t result; // 0x804a689
    result = 0;
    // 0x804a682
    return result;
}

// Address range: 0x804a68a - 0x804a692
// Demangled:     std::_Rb_tree_node<std::pair<char const, int> > * & && std::forward<std::_Rb_tree_node<std::pair<char const, int> > * &>(std::remove_reference<std::_Rb_tree_node<std::pair<char const, int> > * &>::type &)
int32_t _ZSt7forwardIRPSt13_Rb_tree_nodeISt4pairIKciEEEOT_RNSt16remove_referenceIS7_E4typeE(int32_t result) {
    // 0x804a68a
    return result;
}

// Address range: 0x804a692 - 0x804a6a8
// Demangled:     __gnu_cxx::__aligned_membuf<std::pair<char const, int> >::_M_ptr() const
int32_t _ZNK9__gnu_cxx16__aligned_membufISt4pairIKciEE6_M_ptrEv(int32_t a1) {
    // 0x804a692
    return _ZNK9__gnu_cxx16__aligned_membufISt4pairIKciEE7_M_addrEv(a1);
}

// Address range: 0x804a6a8 - 0x804a6b2
// Demangled:     __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<char const, int> > >::max_size() const
int32_t _ZNK9__gnu_cxx13new_allocatorISt13_Rb_tree_nodeISt4pairIKciEEE8max_sizeEv(int32_t a1) {
    // 0x804a6a8
    return 0xaaaaaaa;
}

// Address range: 0x804a6b2 - 0x804a6fa
int32_t _ZNSt4pairIKciEC1IJOcEJEEESt21piecewise_construct_tSt5tupleIJDpT_EES5_IJDpT0_EE(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x804a6b2
    int32_t v1; // bp+16
    _ZNSt4pairIKciEC1IJOcEJLj0EEJEJEEERSt5tupleIJDpT_EERS4_IJDpT1_EESt12_Index_tupleIJXspT0_EEESD_IJXspT2_EEE((char *)a1, a2, (int32_t)&v1, g6, g4);
    int32_t result; // 0x804a6f9
    result = 0;
    // 0x804a6f8
    return result;
}

// Address range: 0x804a6fa - 0x804a702
// Demangled:     __gnu_cxx::__aligned_membuf<std::pair<char const, int> >::_M_addr() const
int32_t _ZNK9__gnu_cxx16__aligned_membufISt4pairIKciEE7_M_addrEv(int32_t result) {
    // 0x804a6fa
    return result;
}

// Address range: 0x804a702 - 0x804a737
int32_t _ZNSt4pairIKciEC1IJOcEJLj0EEJEJEEERSt5tupleIJDpT_EERS4_IJDpT1_EESt12_Index_tupleIJXspT0_EEESD_IJXspT2_EEE(char * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    int32_t v1 = _ZSt7forwardIOcEOT_RNSt16remove_referenceIS1_E4typeE(_ZSt3getILj0EJOcEERNSt13tuple_elementIXT_ESt5tupleIJDpT0_EEE4typeERS5_(a2)); // 0x804a71a
    int32_t result = (int32_t)a1; // 0x804a725
    *a1 = *(char *)v1;
    *(int32_t *)(result + 4) = 0;
    return result;
}

// Address range: 0x804a737 - 0x804a74e
int32_t _ZSt3getILj0EJOcEERNSt13tuple_elementIXT_ESt5tupleIJDpT0_EEE4typeERS5_(int32_t a1) {
    // 0x804a737
    return _ZSt12__get_helperILj0EOcJEERT0_RSt11_Tuple_implIXT_EJS1_DpT1_EE(a1);
}

// Address range: 0x804a74e - 0x804a764
int32_t _ZSt12__get_helperILj0EOcJEERT0_RSt11_Tuple_implIXT_EJS1_DpT1_EE(int32_t a1) {
    // 0x804a74e
    return _ZNSt11_Tuple_implILj0EJOcEE7_M_headERS1_(a1);
}

// --------------- Dynamically Linked Functions ---------------

// int32_t __cxa_begin_catch(void);
// int32_t __cxa_end_catch(void);
// int32_t __cxa_rethrow(void);
// void __stack_chk_fail(void);
// void _ZdlPv(void * ptr);
// void * _Znwj(unsigned int size);
// int32_t _ZSt17__throw_bad_allocv(void);
// int32_t _ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base(void);
// int32_t _ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base(void);
// int32_t _ZSt29_Rb_tree_insert_and_rebalancebPSt18_Rb_tree_node_baseS0_RS_(void);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (8.2.0)
// Detected language: C++
// Detected functions: 103
// Decompilation date: 2018-09-21 12:58:39
